name: Linux Releases

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install System dependencies and LaTeX
        shell: bash
        run: |
          set -x
          echo "Using Apt to install dependencies"
          sudo apt-get update
#           sudo apt-get install nothing?

      - name: Configure CMake
        working-directory: ./build
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release ../

      - name: Build Package
        working-directory: ./build
        shell: bash
        run: cmake --build . --target package -j 2

      - name: Upload Package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/CmakePythonPackaging-*-Linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
