name: Linux Testing

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install System dependencies
        shell: bash
        run: |
          set -x
          echo "Using Apt to install dependencies"
          sudo apt-get update
          sudo apt install make gcc libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev ubuntu-restricted-extras libgstreamer-plugins-base1.0-dev

      - name: Install Python Dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        working-directory: ./build
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release ../

      - name: Build Project
        working-directory: ./build
        shell: bash
        run: cmake --build . -j 2

      - name: Packaging
        working-directory: ./build
        shell: bash
        run: cpack -G TGZ

#      - name: Upload Package
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: build/CmakeAppWithPythonPackaging-*
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
