name: Testing

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            pyinstall_args: ""
            wxpython: https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-18.04/wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl
            generator: TGZ
            cmake_extra_args: ""
            cpack_extra_args: ""
          - os: ubuntu-18.04
            pyinstall_args: ""
            wxpython: https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-18.04/wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl
            generator: TGZ
            cmake_extra_args: ""
            cpack_extra_args: ""
          - os: macos-10.15
            pyinstall_args: --onefile --windowed
            wxpython: wxpython
            generator: TGZ
            cmake_extra_args: ""
            cpack_extra_args: ""
          - os: windows-2019
            pyinstall_args: --windowed
            wxpython: wxpython
            generator: ZIP
            cmake_extra_args: --config Release
            cpack_extra_args: -C Release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        shell: bash
        run: pip install pyinstaller ${{ matrix.wxpython }}

      - name: Create Build Directory
        run: cmake -E make_directory ./cmake-build/

      - name: Configure CMake
        working-directory: ./cmake-build
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release ../

      - name: Build Project
        working-directory: ./cmake-build
        shell: bash
        run: cmake --build . -j 2 ${{ matrix.cmake_extra_args }}

      - name: Packaging
        working-directory: ./cmake-build
        shell: bash
        run: cpack -G ${{ matrix.generator }} ${{ matrix.cpack_extra_args }}
